FROM theborakompanioni/vishy:master
# local development maven docker image
#FROM tbk/vishy-server-web
MAINTAINER Thebora Kompanioni

COPY ./application.yml application.yml
#COPY ./postgresql-9.4.1211.jar /opt/app/lib/postgresql.jar
